package Examen2P2_LloydCooperr;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frameMain extends javax.swing.JFrame {
    private ArrayList<Tecnicos> tecnicos = new ArrayList();
    private ArrayList<Computadora> computadoras = new ArrayList();
    private ArrayList<RAM> RAM = new ArrayList();
    private ArrayList<DiscoDuro> discosDuros = new ArrayList();
    private ArrayList<Bateria> baterias = new ArrayList();
    private ArrayList<Pantalla> pantallas = new ArrayList();
    private ArrayList<Teclado> teclados = new ArrayList();
    private ArrayList<Procesador> procesadors = new ArrayList();
    
    /**
     * Creates new form frameMain
     */
    public frameMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogCRUDS = new javax.swing.JDialog();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        panelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        panelCrearComputadora = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        comboBoxRam = new javax.swing.JComboBox<>();
        tfNumeroSerie = new javax.swing.JTextField();
        comboBoxProcesador = new javax.swing.JComboBox<>();
        tfYear = new javax.swing.JTextField();
        comboBoxBateria = new javax.swing.JComboBox<>();
        tfColor = new javax.swing.JTextField();
        comboBoxPantalla = new javax.swing.JComboBox<>();
        tfMaterial = new javax.swing.JTextField();
        comboBoxTeclado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        comboBoxDiscoDuro = new javax.swing.JComboBox<>();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnCrearComputadora = new javax.swing.JButton();
        panelCrearTecnico = new javax.swing.JPanel();
        tfNombreTecnico = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfEdadTecnico = new javax.swing.JTextField();
        tfGeneroTecnico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCrearTecnico = new javax.swing.JButton();
        panelCrearParte = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnRAM = new javax.swing.JButton();
        btnDiscoDuro = new javax.swing.JButton();
        btnBateria = new javax.swing.JButton();
        btnTeclado = new javax.swing.JButton();
        btnPantalla = new javax.swing.JButton();
        btnProcesador = new javax.swing.JButton();
        panelModificarPC = new javax.swing.JPanel();
        panelModificarTecnico = new javax.swing.JPanel();
        tfGeneroTecnico1 = new javax.swing.JTextField();
        tfNombreTecnico1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfEdadTecnico1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnModificarTecnico = new javax.swing.JButton();
        comboBoxTecnicos = new javax.swing.JComboBox<>();
        dialogSimulacion = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        comboBoxPCs = new javax.swing.JComboBox<>();
        comboBoxTecnicosSimulacion = new javax.swing.JComboBox<>();
        progressBarSimulacion = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnCRUDs = new javax.swing.JButton();
        btnSimulacion = new javax.swing.JButton();

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Computadoras ensambladas", "Tecnicos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Principal", panelPrincipal);

        panelCrearComputadora.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Crear computadora");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Numero de serie");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Año");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Color");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Material");

        btnCrearComputadora.setText("Crear computadora");
        btnCrearComputadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearComputadoraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCrearComputadoraLayout = new javax.swing.GroupLayout(panelCrearComputadora);
        panelCrearComputadora.setLayout(panelCrearComputadoraLayout);
        panelCrearComputadoraLayout.setHorizontalGroup(
            panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearComputadoraLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearComputadoraLayout.createSequentialGroup()
                        .addGroup(panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCrearComputadoraLayout.createSequentialGroup()
                                .addGroup(panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCrearComputadoraLayout.createSequentialGroup()
                                        .addGroup(panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(tfNumeroSerie, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE))
                                    .addGroup(panelCrearComputadoraLayout.createSequentialGroup()
                                        .addComponent(tfColor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCrearComputadoraLayout.createSequentialGroup()
                                        .addComponent(comboBoxPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboBoxProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCrearComputadoraLayout.createSequentialGroup()
                                        .addComponent(comboBoxBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboBoxTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCrearComputadoraLayout.createSequentialGroup()
                                        .addComponent(comboBoxRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboBoxDiscoDuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(112, 112, 112))
                            .addGroup(panelCrearComputadoraLayout.createSequentialGroup()
                                .addComponent(tfMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelCrearComputadoraLayout.createSequentialGroup()
                        .addGroup(panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCrearComputadoraLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCrearComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearComputadoraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(211, 211, 211))
        );
        panelCrearComputadoraLayout.setVerticalGroup(
            panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearComputadoraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(56, 56, 56)
                .addGroup(panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(comboBoxRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDiscoDuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnCrearComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jTabbedPane3.addTab("Crear computadora", panelCrearComputadora);

        panelCrearTecnico.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Edad");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Genero");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Crear tecnico");

        btnCrearTecnico.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearTecnico.setText("Crear tecnico");
        btnCrearTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearTecnicoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCrearTecnicoLayout = new javax.swing.GroupLayout(panelCrearTecnico);
        panelCrearTecnico.setLayout(panelCrearTecnicoLayout);
        panelCrearTecnicoLayout.setHorizontalGroup(
            panelCrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearTecnicoLayout.createSequentialGroup()
                .addGroup(panelCrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearTecnicoLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel5))
                    .addGroup(panelCrearTecnicoLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(panelCrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelCrearTecnicoLayout.createSequentialGroup()
                                    .addGroup(panelCrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelCrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfEdadTecnico)
                                        .addComponent(tfGeneroTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panelCrearTecnicoLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfNombreTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnCrearTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelCrearTecnicoLayout.setVerticalGroup(
            panelCrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearTecnicoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(49, 49, 49)
                .addGroup(panelCrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombreTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfEdadTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfGeneroTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnCrearTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Crear tecnico", panelCrearTecnico);

        panelCrearParte.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Crear parte");

        btnRAM.setText("RAM");
        btnRAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRAMMouseClicked(evt);
            }
        });

        btnDiscoDuro.setText("Disco duro");
        btnDiscoDuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDiscoDuroMouseClicked(evt);
            }
        });

        btnBateria.setText("Bateria");
        btnBateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBateriaMouseClicked(evt);
            }
        });

        btnTeclado.setText("Teclado");
        btnTeclado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTecladoMouseClicked(evt);
            }
        });

        btnPantalla.setText("Pantalla");
        btnPantalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPantallaMouseClicked(evt);
            }
        });

        btnProcesador.setText("Procesador");
        btnProcesador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProcesadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCrearParteLayout = new javax.swing.GroupLayout(panelCrearParte);
        panelCrearParte.setLayout(panelCrearParteLayout);
        panelCrearParteLayout.setHorizontalGroup(
            panelCrearParteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearParteLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(panelCrearParteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(panelCrearParteLayout.createSequentialGroup()
                        .addGroup(panelCrearParteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCrearParteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDiscoDuro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearParteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        panelCrearParteLayout.setVerticalGroup(
            panelCrearParteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearParteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(68, 68, 68)
                .addGroup(panelCrearParteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiscoDuro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelCrearParteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Crear parte", panelCrearParte);

        panelModificarPC.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelModificarPCLayout = new javax.swing.GroupLayout(panelModificarPC);
        panelModificarPC.setLayout(panelModificarPCLayout);
        panelModificarPCLayout.setHorizontalGroup(
            panelModificarPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        panelModificarPCLayout.setVerticalGroup(
            panelModificarPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Modificar computadora", panelModificarPC);

        panelModificarTecnico.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nombre");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Edad");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Genero");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Modificar tecnico");

        btnModificarTecnico.setText("Modificar tecnico");
        btnModificarTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarTecnicoMouseClicked(evt);
            }
        });

        comboBoxTecnicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout panelModificarTecnicoLayout = new javax.swing.GroupLayout(panelModificarTecnico);
        panelModificarTecnico.setLayout(panelModificarTecnicoLayout);
        panelModificarTecnicoLayout.setHorizontalGroup(
            panelModificarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarTecnicoLayout.createSequentialGroup()
                .addGroup(panelModificarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarTecnicoLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel14))
                    .addGroup(panelModificarTecnicoLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(panelModificarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelModificarTecnicoLayout.createSequentialGroup()
                                .addGroup(panelModificarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelModificarTecnicoLayout.createSequentialGroup()
                                        .addGroup(panelModificarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelModificarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfEdadTecnico1)
                                            .addComponent(tfGeneroTecnico1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelModificarTecnicoLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfNombreTecnico1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBoxTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnModificarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        panelModificarTecnicoLayout.setVerticalGroup(
            panelModificarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarTecnicoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addGap(68, 68, 68)
                .addGroup(panelModificarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfNombreTecnico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelModificarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfEdadTecnico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelModificarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfGeneroTecnico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnModificarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Modificar tecnico", panelModificarTecnico);

        javax.swing.GroupLayout dialogCRUDSLayout = new javax.swing.GroupLayout(dialogCRUDS.getContentPane());
        dialogCRUDS.getContentPane().setLayout(dialogCRUDSLayout);
        dialogCRUDSLayout.setHorizontalGroup(
            dialogCRUDSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        dialogCRUDSLayout.setVerticalGroup(
            dialogCRUDSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(comboBoxPCs, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxTecnicosSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(progressBarSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxPCs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTecnicosSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(progressBarSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogSimulacionLayout = new javax.swing.GroupLayout(dialogSimulacion.getContentPane());
        dialogSimulacion.getContentPane().setLayout(dialogSimulacionLayout);
        dialogSimulacionLayout.setHorizontalGroup(
            dialogSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogSimulacionLayout.setVerticalGroup(
            dialogSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Pantalla principal");

        btnCRUDs.setText("CRUDs");
        btnCRUDs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCRUDsMouseClicked(evt);
            }
        });

        btnSimulacion.setText("Simulacion");
        btnSimulacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimulacionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(178, 178, 178))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnCRUDs, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(btnSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel15)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCRUDs, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(btnSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearTecnicoMouseClicked
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        String nombre = tfNombreTecnico.getText();
        String edad = tfEdadTecnico.getText();
        String genero = tfGeneroTecnico.getText();
        
        Object[] fila = {null,nombre};
        
        model.addRow(fila); 
        
        tecnicos.add(new Tecnicos(nombre, edad, genero));
        JOptionPane.showMessageDialog(dialogCRUDS, "Tecnico creado correctamente");
        tfNombreTecnico.setText("");
        tfEdadTecnico.setText("");
        tfGeneroTecnico.setText("");
        comboBoxTecnicos.addItem(nombre);
    }//GEN-LAST:event_btnCrearTecnicoMouseClicked

    private void btnRAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRAMMouseClicked
        int tam = Integer.parseInt(JOptionPane.showInputDialog(dialogCRUDS, "Ingrese el tamaño de la RAM"));
        String marca = JOptionPane.showInputDialog(dialogCRUDS, "Ingrese la marca de la RAM");
        RAM.add(new RAM(tam, marca, 5));
        JOptionPane.showMessageDialog(dialogCRUDS, "RAM creada correctamente");
        String ramInfo = tam + "GB - " + marca;
        comboBoxRam.addItem(ramInfo);
    }//GEN-LAST:event_btnRAMMouseClicked

    private void btnDiscoDuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiscoDuroMouseClicked
        int tam = Integer.parseInt(JOptionPane.showInputDialog(dialogCRUDS, "Ingrese el tamaño del disco duro"));
        String marca = JOptionPane.showInputDialog(dialogCRUDS, "Ingrese la marca del disco duro");
        discosDuros.add(new DiscoDuro(tam, marca, 5));
        JOptionPane.showMessageDialog(dialogCRUDS, "Disco duro creado correctamente");
        String discoDuroInfo = tam + "GB - " + marca;
        comboBoxDiscoDuro.addItem(discoDuroInfo );
    }//GEN-LAST:event_btnDiscoDuroMouseClicked

    private void btnBateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBateriaMouseClicked
        String capacidadHoras = JOptionPane.showInputDialog(dialogCRUDS, "Ingrese la capacidad de la bateria");
        String material = JOptionPane.showInputDialog(dialogCRUDS, "Ingrese el material de la bateria");
        baterias.add(new Bateria(capacidadHoras, material, 5));
        JOptionPane.showMessageDialog(dialogCRUDS, "Bateria creada correctamente");
        String bateriaInfo = capacidadHoras + "hrs" + material;
        comboBoxBateria.addItem(bateriaInfo);
    }//GEN-LAST:event_btnBateriaMouseClicked

    private void btnTecladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTecladoMouseClicked
        String material = JOptionPane.showInputDialog(dialogCRUDS, "Ingrese el material del teclado");
        String color = JOptionPane.showInputDialog(dialogCRUDS, "Ingrese el material del teclado");
        teclados.add(new Teclado(material, color, 10));
        JOptionPane.showMessageDialog(dialogCRUDS, "Teclado creado correctamente");
        String tecladoInfo = material + "\n" + color;
        comboBoxTeclado.addItem(tecladoInfo);
    }//GEN-LAST:event_btnTecladoMouseClicked

    private void btnPantallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPantallaMouseClicked
        int respuesta = JOptionPane.showConfirmDialog(dialogCRUDS, "¿La pantalla es táctil?", "Confirmación", JOptionPane.YES_NO_OPTION);
        boolean tactil = (respuesta == JOptionPane.YES_OPTION);
        String tipo = JOptionPane.showInputDialog(dialogCRUDS, "Ingrese el tipo de pantalla");
        pantallas.add(new Pantalla(tactil, tipo, 5));
        JOptionPane.showMessageDialog(dialogCRUDS, "Pantalla creada correctamente");
        String pantallaInfo = tactil + "\n\n" + tipo;
        comboBoxPantalla.addItem(pantallaInfo);
    }//GEN-LAST:event_btnPantallaMouseClicked

    private void btnProcesadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcesadorMouseClicked
        int numeroNucleos = Integer.parseInt(JOptionPane.showInputDialog(dialogCRUDS, "Ingrese el numero de nucleos del procesador"));
        String velocidad = JOptionPane.showInputDialog(dialogCRUDS, "Ingrese la velocidad del procesador");
        procesadors.add(new Procesador(numeroNucleos, velocidad, 5));
        JOptionPane.showMessageDialog(dialogCRUDS, "Procesador creado correctamente");
        String procesadorInfo = numeroNucleos + "nucleos" + "\n" + velocidad + "GHz";
        comboBoxProcesador.addItem(procesadorInfo);
    }//GEN-LAST:event_btnProcesadorMouseClicked

    private void btnModificarTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarTecnicoMouseClicked
        String nombreSeleccionado = (String) comboBoxTecnicos.getSelectedItem();
        Tecnicos tecnicoSeleccionado = null;

        for (Tecnicos tecnico : tecnicos) {
            if (tecnico.getNombre().equals(nombreSeleccionado)) {
                tecnicoSeleccionado = tecnico;
                break;
            }
        }

        // Verificar si se encontró el técnico seleccionado
        if (tecnicoSeleccionado != null) {
            String nuevoNombre = tecnicoSeleccionado.getNombre();
            String nuevaEdad = tecnicoSeleccionado.getEdad();
            String nuevoGenero = tecnicoSeleccionado.getGenero();

            // Actualizar los datos en el técnico seleccionado
            tecnicoSeleccionado.setNombre(nuevoNombre);
            tecnicoSeleccionado.setEdad(nuevaEdad);
            tecnicoSeleccionado.setGenero(nuevoGenero);
            
            // Actualizar el nombre en la tabla
            DefaultTableModel model = (DefaultTableModel) table1.getModel();
            int rowCount = model.getRowCount();

            for (int i = 0; i < rowCount; i++) {
                String nombreTabla = (String) model.getValueAt(i, 1);
                if (nombreTabla.equals(nombreSeleccionado)) {
                    model.setValueAt(nuevoNombre, i, 1);
                    break;
                }
            }
        }
        JOptionPane.showMessageDialog(dialogCRUDS, "Técnico modificado correctamente");
    }//GEN-LAST:event_btnModificarTecnicoMouseClicked

    private void btnCRUDsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCRUDsMouseClicked
        dialogCRUDS.pack();
        dialogCRUDS.setModal(true);
        dialogCRUDS.setLocationRelativeTo(this);
        dialogCRUDS.setVisible(true);
    }//GEN-LAST:event_btnCRUDsMouseClicked

    private void btnCrearComputadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearComputadoraMouseClicked
        String numSerie = tfNumeroSerie.getText();
        String year = tfEdadTecnico.getText();
        String color = tfColor.getText();
        String material = tfMaterial.getText();

        int selectedIndexRam = comboBoxRam.getSelectedIndex();
        int selectedIndexPantalla = comboBoxPantalla.getSelectedIndex();
        int selectedIndexTeclado = comboBoxTeclado.getSelectedIndex();
        int selectedIndexDiscoDuro = comboBoxDiscoDuro.getSelectedIndex();
        int selectedIndexBateria = comboBoxBateria.getSelectedIndex();
        int selectedIndexProcesador = comboBoxProcesador.getSelectedIndex();

        ArrayList<Parte> partes = new ArrayList<>();

        // Obtener los objetos de las ArrayList de partes utilizando los índices seleccionados
        if (selectedIndexRam != -2) {
            partes.add(RAM.get(selectedIndexRam));
        }
        if (selectedIndexPantalla != -2) {
            partes.add(pantallas.get(selectedIndexPantalla));
        }
        if (selectedIndexTeclado != -2) {
            partes.add(teclados.get(selectedIndexTeclado));
        }
        if (selectedIndexDiscoDuro != -2) {
            partes.add(discosDuros.get(selectedIndexDiscoDuro));
        }
        if (selectedIndexBateria != -2) {
            partes.add(baterias.get(selectedIndexBateria));
        }
        if (selectedIndexProcesador != -2) {
            partes.add(procesadors.get(selectedIndexProcesador));
        }

        computadoras.add(new Computadora(numSerie, year, color, material, partes));

        JOptionPane.showMessageDialog(null, "Computadora creada correctamente");

    }//GEN-LAST:event_btnCrearComputadoraMouseClicked

    private void btnSimulacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimulacionMouseClicked
        dialogSimulacion.pack();
        dialogSimulacion.setModal(true);
        dialogSimulacion.setLocationRelativeTo(this);
        dialogSimulacion.setVisible(true);
    }//GEN-LAST:event_btnSimulacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBateria;
    private javax.swing.JButton btnCRUDs;
    private javax.swing.JButton btnCrearComputadora;
    private javax.swing.JButton btnCrearTecnico;
    private javax.swing.JButton btnDiscoDuro;
    private javax.swing.JButton btnModificarTecnico;
    private javax.swing.JButton btnPantalla;
    private javax.swing.JButton btnProcesador;
    private javax.swing.JButton btnRAM;
    private javax.swing.JButton btnSimulacion;
    private javax.swing.JButton btnTeclado;
    private javax.swing.JComboBox<String> comboBoxBateria;
    private javax.swing.JComboBox<String> comboBoxDiscoDuro;
    private javax.swing.JComboBox<String> comboBoxPCs;
    private javax.swing.JComboBox<String> comboBoxPantalla;
    private javax.swing.JComboBox<String> comboBoxProcesador;
    private javax.swing.JComboBox<String> comboBoxRam;
    private javax.swing.JComboBox<String> comboBoxTeclado;
    private javax.swing.JComboBox<String> comboBoxTecnicos;
    private javax.swing.JComboBox<String> comboBoxTecnicosSimulacion;
    private javax.swing.JDialog dialogCRUDS;
    private javax.swing.JDialog dialogSimulacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JPanel panelCrearComputadora;
    private javax.swing.JPanel panelCrearParte;
    private javax.swing.JPanel panelCrearTecnico;
    private javax.swing.JPanel panelModificarPC;
    private javax.swing.JPanel panelModificarTecnico;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JProgressBar progressBarSimulacion;
    private javax.swing.JTable table1;
    private javax.swing.JTextField tfColor;
    private javax.swing.JTextField tfEdadTecnico;
    private javax.swing.JTextField tfEdadTecnico1;
    private javax.swing.JTextField tfGeneroTecnico;
    private javax.swing.JTextField tfGeneroTecnico1;
    private javax.swing.JTextField tfMaterial;
    private javax.swing.JTextField tfNombreTecnico;
    private javax.swing.JTextField tfNombreTecnico1;
    private javax.swing.JTextField tfNumeroSerie;
    private javax.swing.JTextField tfYear;
    // End of variables declaration//GEN-END:variables
}
